name: Deploy staging

on:
  push:
    branches:
      - redesign

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Deploy to staging server folder
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          source: "*"
          target: "/var/www/policycamp-staging"

